import { Metadata } from 'next';
import Link from 'next/link';
import AnimatedText from '../components/AnimatedText';
import { HireMe } from '../components/HireMe';
import { GithubIcon, LinkArrow } from '../components/Icons';
import { Layout } from '../components/Layout';
import ThemeImage from '../components/ThemeImage';
import TransitionEffect from '../components/TransitionEffect';

export const metadata: Metadata = {
  title: 'Joji.Iba Portfolio with Next.js',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <>
      <TransitionEffect />
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full p-8">
              <ThemeImage />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Try&Error! 挑戦することで、 自分を超える。"
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />
              <p className="my-4 text-base font-medium md:text-sm sm:!text-xs">
                モダンな技術研磨に励んでいるWeb Developerです。
                React/Next.js、TypeScript、Go/Gin、Docker、AWS、Terraformを中心に学んでいます。
                革新的なアイデアと共に、ユーザーにとって「面白い」「使いやすい」「ハイパフォーマンス」なWebアプリケーション開発に専念致します。
                これまで携わったプロジェクトや個人開発の作品集をご覧下さい！
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/dummy.pdf"
                  target={'_blank'}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold border-2 border-solid border-transparent capitalize hover:bg-light hover:text-dark hover:bg-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark  hover:dark:text-light hover:dark:border-light sm:!p-2 sm:!px-4 sm:!text-base"
                  download={true}
                >
                  Resume <LinkArrow className={'!w-6 ml-1'} />
                </Link>
                <Link
                  href="/contact"
                  // target={'_blank'}
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base"
                >
                  Contact
                </Link>
                <Link
                  href="https://github.com/joji-iba/My-SPA-Portfolio"
                  target={'_blank'}
                  className="ml-4"
                >
                  <GithubIcon className="!w-10" />
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        {/* <div className="absolute right-8 bottom-8 inline-block w-24 md:hidden">
          <Image src={LightBulbSvg} alt="Joji Iba" className="w-full h-auto" />
        </div> */}
      </main>
    </>
  );
}
